[package]
name = "day_07"
version = "0.1.0"
authors = ["ruiramos <rui@ometria.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
permutohedron = "0.2"
